### ISSUE TITLE
Change base image to reduce size?

### ISSUE THREAD

**Issue by asmaloney** [otherguy/docker-dropbox#20]
Building this results in a 1.26GB image which seems quite excessive for what this container is doing. (Space is an issue for some deployments.)

Would you consider switching to `alpine`?

**Comment by otherguy** [comment]
Hi @asmaloney,

the `otherguy/dropbox:latest` image should actually be 1.05GB but I see what you mean.

`alpine:latest` _is_ very small at only 5.61MB but `debian:buster` also only takes up 114MB.

Dropbox itself is actually quite large. Just the `bin` folder takes up almost 200 MB:

```shell
$ du -sh /opt/dropbox/*
191M /opt/dropbox/bin
```

Additionally, the dropbox daemon has some hard dependencies, like `ca-certificates` and `curl` (and not just during building/installing but also during runtime). `tzdata` and the locale packages also take up several hundred megabytes.

I will take a look at remove the locale package and going with `C.UTF-8`, which should bring the image to around 800MB.

Additionally I can try alpine, but from memory, it was an insane amount of work getting Dropbox running on alpine. Dropbox requires `glibc` which needs some hackery to work on alpine. I will try, but if the space savings are not at least 50% (so 400MB instead of the above mentioned 800MB) it's not going to be worth it.

**Comment by asmaloney** [comment]
> should actually be 1.05GB

It's by far the largest image I have to deal with - and I have apache installed on some of them :-)

> Dropbox itself is actually quite large.

Ah yeah - that's nuts.

> look at remove the locale package

That would be great.

Another option that might help if `alpine` is a no-go might be `buster-slim`? Easy to change and might shave off a bit (depending on dependencies of course).

Thanks Alexander!

**Comment by otherguy** [comment]
`buster-slim` is actually a great idea. It really shaves off a lot. Just pushed `1.8.0` which reduces image size to 686MB. That is substantially better! Thanks for the tip!

**Comment by asmaloney** [comment]
Awesome work. Thanks Alexander!
